# Generated by Django 5.0.6 on 2024-07-10 11:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_vendors_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
