# Generated by Django 5.0.6 on 2024-07-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='duration',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
