# Generated by Django 5.0.6 on 2024-07-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_events_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
