# Generated by Django 5.0.6 on 2024-07-31 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_tickettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettransaction',
            name='price_of_ticket',
        ),
    ]
