# Generated by Django 5.0.6 on 2024-07-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_remove_tickettransaction_price_of_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettransaction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
