# Generated by Django 5.0.6 on 2024-09-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_tickettransaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettransaction',
            name='date',
            field=models.DateField(),
        ),
    ]
