# Generated by Django 5.0.6 on 2025-01-16 07:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_alter_tickettransaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('secondName', models.CharField(max_length=100)),
                ('phoneNumber', models.IntegerField(null=True)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('dateJoined', models.DateField()),
                ('averageRating', models.IntegerField(null=True)),
                ('uniformColor', models.CharField(max_length=100, null=True)),
                ('workPermit', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
        migrations.DeleteModel(
            name='TicketTransaction',
        ),
        migrations.DeleteModel(
            name='Vendors',
        ),
    ]
