# Generated by Django 5.0.6 on 2025-01-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_personnel_delete_events_delete_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='firstName',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='secondName',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='uniformColor',
            field=models.CharField(null=True),
        ),
    ]
