# Generated by Django 5.0.6 on 2025-01-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_alter_personnel_firstname_alter_personnel_secondname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='secondName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='workPermit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
