# Generated by Django 5.0.6 on 2025-01-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_alter_personnel_firstname_alter_personnel_secondname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentErrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eatery', models.CharField(max_length=100)),
                ('foodChoices', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('clientPhoneNumber', models.IntegerField(max_length=100)),
                ('receiverFullName', models.CharField(max_length=100)),
            ],
        ),
    ]
