# Generated by Django 5.0.6 on 2025-01-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_alter_senterrands_clientphonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomErrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errandDescription', models.CharField(max_length=100)),
                ('pickupAddress', models.CharField(max_length=100)),
                ('dropOffAddress', models.CharField(max_length=100)),
                ('clientPhoneNumber', models.IntegerField()),
                ('receiverFullName', models.CharField(max_length=100)),
            ],
        ),
    ]
