# Generated by Django 5.0.6 on 2025-01-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_customerrands'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryShoppingErrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=100)),
                ('orders', models.CharField(max_length=150)),
                ('deliveryAddress', models.CharField(max_length=100)),
                ('clientPhoneNumber', models.IntegerField()),
                ('receiverFullName', models.CharField(max_length=100)),
            ],
        ),
    ]
